[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*

[FILTER]
    Name modify
    Match *
    Add environment demo

[OUTPUT]
    Name grafana-loki
    Match *
    Url https://logs-prod-us-central1.grafana.net/loki/api/v1/push
    TenantID YOUR_GRAFANA_USER_ID
    Labels job=fluentbit
    LineFormat json
    Header Authorization Bearer YOUR_GRAFANA_API_KEY